FROM wordpress:6.8.2-php8.1-apache
LABEL maintainer="paulserban.eu"

# do not install this on production images
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

RUN rm -rf /var/lib/apt/lists/* \
  && mkdir -p /var/www/html/wp-content \
  && chown -R www-data:www-data /var/www/html/wp-content

COPY ./backend/cms/hello-wordpress-core-setup-cms/src /var/www/html
COPY ./backend/cms/hello-wordpress-core-setup-cms/src/wp-config.php /var/www/html/wp-config.php

RUN mkdir -p /var/www/html/wp-content/uploads
COPY ./backend/cms/hello-wordpress-core-setup-cms/src/wp-content/uploads /var/www/html/wp-content/uploads

RUN chown -R www-data:www-data /var/www/html/wp-content/uploads \
    && chown -R www-data:www-data /var/www/html/wp-content/themes \
    && chown -R www-data:www-data /var/www/html/wp-content/plugins \
    && chown -R www-data:www-data /var/www/html/wp-config.php \
    && chown -R www-data:www-data /var/www/html
